#!/usr/bin/env bash
# PowerShop Analytics — Linux/macOS installer
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/alvarolobato/powershop-analytics/main/deploy/install.sh | bash
#
# Environment overrides:
#   PS_ANALYTICS_HOME  — installation directory (default: $HOME/.powershop-analytics)
#   VERSION            — release tag to install (default: latest)
#
set -euo pipefail

REPO="alvarolobato/powershop-analytics"
PROJECT_DIR="${PS_ANALYTICS_HOME:-$HOME/.powershop-analytics}"
RELEASE_BASE="https://github.com/${REPO}/releases/download"
API_BASE="https://api.github.com/repos/${REPO}"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
info()    { printf '\033[1;34m[INFO]\033[0m  %s\n' "$*"; }
success() { printf '\033[1;32m[OK]\033[0m    %s\n' "$*"; }
warn()    { printf '\033[1;33m[WARN]\033[0m  %s\n' "$*"; }
die()     { printf '\033[1;31m[ERROR]\033[0m %s\n' "$*" >&2; exit 1; }

prompt_required() {
  local label="$1" var_name="$2" value=""
  while [[ -z "$value" ]]; do
    read -rp "  ${label}: " value
  done
  printf '%s' "$value"
}

prompt_default() {
  local label="$1" default="$2" value=""
  read -rp "  ${label} [${default}]: " value
  printf '%s' "${value:-$default}"
}

random_password() {
  # Generate a 24-char random password using /dev/urandom or openssl
  if command -v openssl &>/dev/null; then
    openssl rand -base64 18 | tr -dc 'A-Za-z0-9' | head -c 24
  else
    tr -dc 'A-Za-z0-9' </dev/urandom | head -c 24
  fi
}

# ---------------------------------------------------------------------------
# Prerequisite checks
# ---------------------------------------------------------------------------
check_prerequisites() {
  info "Checking prerequisites..."

  if ! command -v docker &>/dev/null; then
    die "Docker is not installed. Please install Docker: https://docs.docker.com/get-docker/"
  fi

  if ! docker compose version &>/dev/null 2>&1; then
    die "'docker compose' (v2) is not available. Please install Docker Compose v2."
  fi

  if ! command -v curl &>/dev/null; then
    die "curl is required but not found. Please install curl."
  fi

  success "Prerequisites OK (docker $(docker --version | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1), compose $(docker compose version --short 2>/dev/null || echo 'v2'))"
}

# ---------------------------------------------------------------------------
# Resolve version
# ---------------------------------------------------------------------------
resolve_version() {
  if [[ -n "${VERSION:-}" ]]; then
    echo "$VERSION"
    return
  fi
  info "Fetching latest release version..."
  local tag
  tag=$(curl -fsSL "${API_BASE}/releases/latest" | grep '"tag_name"' | sed -E 's/.*"tag_name": *"([^"]+)".*/\1/')
  if [[ -z "$tag" ]]; then
    die "Could not determine latest release. Set VERSION=<tag> to override."
  fi
  echo "$tag"
}

# ---------------------------------------------------------------------------
# Download a release asset
# ---------------------------------------------------------------------------
download_asset() {
  local version="$1" filename="$2" dest="$3"
  local url="${RELEASE_BASE}/${version}/${filename}"
  info "Downloading ${filename}..."
  curl -fsSL "$url" -o "$dest" || die "Failed to download ${url}"
}

# ---------------------------------------------------------------------------
# Interactive .env setup
# ---------------------------------------------------------------------------
create_env() {
  local env_file="$1"
  local pg_pass
  pg_pass=$(random_password)

  echo ""
  info "Configuring .env — press Enter to accept defaults."
  echo ""

  local p4d_host p4d_user p4d_password postgres_password openrouter_key
  p4d_host=$(prompt_required "4D server hostname or IP" "P4D_HOST")
  p4d_user=$(prompt_required "4D SQL username" "P4D_USER")
  p4d_password=$(prompt_required "4D SQL password" "P4D_PASSWORD")
  postgres_password=$(prompt_default "PostgreSQL password" "$pg_pass")
  openrouter_key=$(prompt_required "OpenRouter API key (for WrenAI LLM)" "OPENROUTER_API_KEY")

  cat >"$env_file" <<EOF
# PowerShop Analytics — environment configuration
# Generated by install.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Edit this file to change settings; re-run install.sh to reconfigure.

# ---------------------------------------------------------------------------
# 4D source database
# ---------------------------------------------------------------------------
P4D_HOST=${p4d_host}
P4D_PORT=19812
P4D_USER=${p4d_user}
P4D_PASSWORD=${p4d_password}

# SOAP endpoint (usually same host, port 8080)
SOAP_URL=http://${p4d_host}:8080/4DSOAP/
SOAP_WSDL=http://${p4d_host}:8080/4DSOAP/?wsdl

# ---------------------------------------------------------------------------
# PostgreSQL (mirror)
# ---------------------------------------------------------------------------
POSTGRES_USER=postgres
POSTGRES_PASSWORD=${postgres_password}
POSTGRES_DB=powershop

# ---------------------------------------------------------------------------
# ETL scheduler
# ---------------------------------------------------------------------------
ETL_CRON_HOUR=2

# ---------------------------------------------------------------------------
# WrenAI / LLM
# ---------------------------------------------------------------------------
OPENROUTER_API_KEY=${openrouter_key}
WREN_LLM_MODEL=openrouter/anthropic/claude-sonnet-4-20250514

# WrenAI UI port
HOST_PORT=3000

# ---------------------------------------------------------------------------
# WrenAI service versions (leave as-is unless upgrading manually)
# ---------------------------------------------------------------------------
WREN_BOOTSTRAP_VERSION=0.1.5
WREN_ENGINE_VERSION=0.22.0
IBIS_SERVER_VERSION=0.22.0
WREN_AI_SERVICE_VERSION=0.29.0
WREN_UI_VERSION=0.32.2
WREN_PRODUCT_VERSION=0.29.1
AI_SERVICE_FORWARD_PORT=5555
WREN_ENGINE_PORT=8080
WREN_ENGINE_SQL_PORT=7432
IBIS_SERVER_PORT=8000
WREN_AI_SERVICE_PORT=5555

# Platform — set to linux/arm64 on Apple Silicon if images support it
PLATFORM=linux/amd64

# Telemetry (set to false to disable)
TELEMETRY_ENABLED=true
EOF
  success ".env created"
}

# ---------------------------------------------------------------------------
# Install CLI wrapper
# ---------------------------------------------------------------------------
install_cli() {
  local version="$1"
  local tmp_cli
  tmp_cli=$(mktemp)
  download_asset "$version" "ps-analytics" "$tmp_cli"
  chmod +x "$tmp_cli"

  # Inject project dir into the wrapper
  sed -i.bak "s|^PS_ANALYTICS_HOME=.*|PS_ANALYTICS_HOME=\"${PROJECT_DIR}\"|" "$tmp_cli" 2>/dev/null || true
  rm -f "${tmp_cli}.bak"

  local install_dir
  if [[ -w "/usr/local/bin" ]]; then
    install_dir="/usr/local/bin"
  elif sudo -n true 2>/dev/null; then
    install_dir="/usr/local/bin"
    sudo install -m 0755 "$tmp_cli" "${install_dir}/ps-analytics"
    rm -f "$tmp_cli"
    success "CLI installed to ${install_dir}/ps-analytics (via sudo)"
    return
  else
    install_dir="$HOME/.local/bin"
    mkdir -p "$install_dir"
  fi

  install -m 0755 "$tmp_cli" "${install_dir}/ps-analytics"
  rm -f "$tmp_cli"
  success "CLI installed to ${install_dir}/ps-analytics"

  # Warn if ~/.local/bin is not on PATH
  if [[ "$install_dir" == "$HOME/.local/bin" ]] && ! echo "$PATH" | grep -q "$HOME/.local/bin"; then
    warn "Add ~/.local/bin to your PATH:"
    warn "  echo 'export PATH=\"\$HOME/.local/bin:\$PATH\"' >> ~/.bashrc"
  fi
}

# ---------------------------------------------------------------------------
# Write installed version file
# ---------------------------------------------------------------------------
write_version() {
  local version="$1"
  echo "$version" >"${PROJECT_DIR}/.version"
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
main() {
  echo ""
  echo "=================================================="
  echo "  PowerShop Analytics — Installer"
  echo "=================================================="
  echo ""

  check_prerequisites

  local version
  version=$(resolve_version)
  info "Installing version: ${version}"

  # Create project directory and data subdirs
  mkdir -p \
    "${PROJECT_DIR}/data/postgres" \
    "${PROJECT_DIR}/data/qdrant" \
    "${PROJECT_DIR}/data/wren"
  success "Project directory: ${PROJECT_DIR}"

  # Download compose and config files
  download_asset "$version" "docker-compose.prod.yml" "${PROJECT_DIR}/docker-compose.yml"
  download_asset "$version" "wren-config.yaml"        "${PROJECT_DIR}/wren-config.yaml"
  success "Stack files downloaded"

  # Configure .env
  if [[ -f "${PROJECT_DIR}/.env" ]]; then
    warn ".env already exists — skipping interactive setup (delete it to reconfigure)"
  else
    create_env "${PROJECT_DIR}/.env"
  fi

  # Install CLI
  install_cli "$version"
  write_version "$version"

  echo ""
  echo "=================================================="
  success "Installation complete!"
  echo ""
  echo "  Next steps:"
  echo "    1. Start the stack:    ps-analytics up"
  echo "    2. Check status:       ps-analytics status"
  echo "    3. Open WrenAI UI:     ps-analytics open"
  echo "    4. Run ETL sync now:   ps-analytics etl run"
  echo ""
  echo "  Project directory: ${PROJECT_DIR}"
  echo "=================================================="
  echo ""
}

main "$@"
