# PowerShop Analytics — Windows PowerShell Installer
#
# Usage (run in PowerShell as user, not admin required):
#   irm https://raw.githubusercontent.com/alvarolobato/powershop-analytics/main/deploy/install.ps1 | iex
#
# Environment overrides:
#   $env:PS_ANALYTICS_HOME  — installation directory (default: %APPDATA%\powershop-analytics)
#   $env:VERSION            — release tag to install (default: latest)
#
[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$Repo        = "alvarolobato/powershop-analytics"
$ProjectDir  = if ($env:PS_ANALYTICS_HOME) { $env:PS_ANALYTICS_HOME } else { Join-Path $env:APPDATA "powershop-analytics" }
$ReleaseBase = "https://github.com/$Repo/releases/download"
$ApiBase     = "https://api.github.com/repos/$Repo"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
function Write-Info    { param($Msg) Write-Host "[INFO]  $Msg" -ForegroundColor Cyan }
function Write-Ok      { param($Msg) Write-Host "[OK]    $Msg" -ForegroundColor Green }
function Write-Warn    { param($Msg) Write-Host "[WARN]  $Msg" -ForegroundColor Yellow }
function Write-Fatal   { param($Msg) Write-Host "[ERROR] $Msg" -ForegroundColor Red; exit 1 }

function Prompt-Required {
  param([string]$Label)
  $value = ""
  while ([string]::IsNullOrWhiteSpace($value)) {
    $value = Read-Host "  $Label"
  }
  return $value
}

function Prompt-Default {
  param([string]$Label, [string]$Default)
  $value = Read-Host "  $Label [$Default]"
  if ([string]::IsNullOrWhiteSpace($value)) { return $Default }
  return $value
}

function New-RandomPassword {
  $chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789'
  -join (1..24 | ForEach-Object { $chars[(Get-Random -Maximum $chars.Length)] })
}

# ---------------------------------------------------------------------------
# Prerequisite checks
# ---------------------------------------------------------------------------
function Test-Prerequisites {
  Write-Info "Checking prerequisites..."

  if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
    Write-Fatal "Docker is not installed. Please install Docker Desktop: https://docs.docker.com/desktop/install/windows-install/"
  }

  $composeCheck = docker compose version 2>&1
  if ($LASTEXITCODE -ne 0) {
    Write-Fatal "'docker compose' (v2) is not available. Please install Docker Desktop with Compose v2."
  }

  Write-Ok "Prerequisites OK"
}

# ---------------------------------------------------------------------------
# Resolve version
# ---------------------------------------------------------------------------
function Resolve-Version {
  if ($env:VERSION) { return $env:VERSION }

  Write-Info "Fetching latest release version..."
  try {
    $release = Invoke-RestMethod -Uri "$ApiBase/releases/latest" -UseBasicParsing
    $tag = $release.tag_name
    if (-not $tag) { Write-Fatal "Could not determine latest release. Set `$env:VERSION to override." }
    return $tag
  } catch {
    Write-Fatal "Failed to fetch release info: $_"
  }
}

# ---------------------------------------------------------------------------
# Download a release asset
# ---------------------------------------------------------------------------
function Get-ReleaseAsset {
  param([string]$Version, [string]$Filename, [string]$Dest)
  $url = "$ReleaseBase/$Version/$Filename"
  Write-Info "Downloading $Filename..."
  try {
    Invoke-WebRequest -Uri $url -OutFile $Dest -UseBasicParsing
  } catch {
    Write-Fatal "Failed to download ${url}: $_"
  }
}

# ---------------------------------------------------------------------------
# Interactive .env setup
# ---------------------------------------------------------------------------
function New-EnvFile {
  param([string]$EnvFile)

  $pgPass = New-RandomPassword
  $timestamp = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")

  Write-Host ""
  Write-Info "Configuring .env — press Enter to accept defaults."
  Write-Host ""

  $p4dHost         = Prompt-Required "4D server hostname or IP"
  $p4dUser         = Prompt-Required "4D SQL username"
  $p4dPassword     = Prompt-Required "4D SQL password"
  $postgresPassword = Prompt-Default "PostgreSQL password" $pgPass
  $openrouterKey   = Prompt-Required "OpenRouter API key (for WrenAI LLM)"

  $envContent = @"
# PowerShop Analytics — environment configuration
# Generated by install.ps1 on $timestamp
# Edit this file to change settings; re-run install.ps1 to reconfigure.

# ---------------------------------------------------------------------------
# 4D source database
# ---------------------------------------------------------------------------
P4D_HOST=$p4dHost
P4D_PORT=19812
P4D_USER=$p4dUser
P4D_PASSWORD=$p4dPassword

# SOAP endpoint (usually same host, port 8080)
SOAP_URL=http://${p4dHost}:8080/4DSOAP/
SOAP_WSDL=http://${p4dHost}:8080/4DSOAP/?wsdl

# ---------------------------------------------------------------------------
# PostgreSQL (mirror)
# ---------------------------------------------------------------------------
POSTGRES_USER=postgres
POSTGRES_PASSWORD=$postgresPassword
POSTGRES_DB=powershop

# ---------------------------------------------------------------------------
# ETL scheduler
# ---------------------------------------------------------------------------
ETL_CRON_HOUR=2

# ---------------------------------------------------------------------------
# WrenAI / LLM
# ---------------------------------------------------------------------------
OPENROUTER_API_KEY=$openrouterKey
WREN_LLM_MODEL=openrouter/anthropic/claude-sonnet-4-20250514

# WrenAI UI port
HOST_PORT=3000

# ---------------------------------------------------------------------------
# WrenAI service versions (leave as-is unless upgrading manually)
# ---------------------------------------------------------------------------
WREN_BOOTSTRAP_VERSION=0.1.5
WREN_ENGINE_VERSION=0.22.0
IBIS_SERVER_VERSION=0.22.0
WREN_AI_SERVICE_VERSION=0.29.0
WREN_UI_VERSION=0.32.2
WREN_PRODUCT_VERSION=0.29.1
AI_SERVICE_FORWARD_PORT=5555
WREN_ENGINE_PORT=8080
WREN_ENGINE_SQL_PORT=7432
IBIS_SERVER_PORT=8000
WREN_AI_SERVICE_PORT=5555

# Platform
PLATFORM=linux/amd64

# Telemetry (set to false to disable)
TELEMETRY_ENABLED=true
"@

  Set-Content -Path $EnvFile -Value $envContent -Encoding UTF8
  Write-Ok ".env created"
}

# ---------------------------------------------------------------------------
# Install CLI wrapper
# ---------------------------------------------------------------------------
function Install-CliWrapper {
  param([string]$Version)

  $cliDir = Join-Path $env:LOCALAPPDATA "powershop-analytics"
  New-Item -ItemType Directory -Force -Path $cliDir | Out-Null

  $destCmd = Join-Path $cliDir "ps-analytics.cmd"
  Get-ReleaseAsset -Version $Version -Filename "ps-analytics.cmd" -Dest $destCmd
  Write-Ok "CLI wrapper downloaded to $destCmd"

  # Add to user PATH if not already present
  $userPath = [System.Environment]::GetEnvironmentVariable("PATH", "User") ?? ""
  if ($userPath -notlike "*$cliDir*") {
    [System.Environment]::SetEnvironmentVariable(
      "PATH",
      "$cliDir;$userPath",
      "User"
    )
    Write-Ok "Added $cliDir to user PATH"
    Write-Warn "Restart your terminal for PATH changes to take effect."
  }
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
function Main {
  Write-Host ""
  Write-Host "==================================================" -ForegroundColor Cyan
  Write-Host "  PowerShop Analytics -- Installer (Windows)"       -ForegroundColor Cyan
  Write-Host "==================================================" -ForegroundColor Cyan
  Write-Host ""

  Test-Prerequisites

  $version = Resolve-Version
  Write-Info "Installing version: $version"

  # Create project directory and data subdirs
  @("data\postgres", "data\qdrant", "data\wren") | ForEach-Object {
    New-Item -ItemType Directory -Force -Path (Join-Path $ProjectDir $_) | Out-Null
  }
  Write-Ok "Project directory: $ProjectDir"

  # Download compose and config files
  Get-ReleaseAsset -Version $version -Filename "docker-compose.prod.yml" -Dest (Join-Path $ProjectDir "docker-compose.yml")
  Get-ReleaseAsset -Version $version -Filename "wren-config.yaml"        -Dest (Join-Path $ProjectDir "wren-config.yaml")
  Write-Ok "Stack files downloaded"

  # Configure .env
  $envFile = Join-Path $ProjectDir ".env"
  if (Test-Path $envFile) {
    Write-Warn ".env already exists — skipping interactive setup (delete it to reconfigure)"
  } else {
    New-EnvFile -EnvFile $envFile
  }

  # Install CLI
  Install-CliWrapper -Version $version

  # Write version file
  Set-Content -Path (Join-Path $ProjectDir ".version") -Value $version -Encoding UTF8

  Write-Host ""
  Write-Host "==================================================" -ForegroundColor Green
  Write-Ok "Installation complete!"
  Write-Host ""
  Write-Host "  Next steps:"
  Write-Host "    1. Restart terminal (PATH update)"
  Write-Host "    2. Start the stack:    ps-analytics up"
  Write-Host "    3. Check status:       ps-analytics status"
  Write-Host "    4. Open WrenAI UI:     ps-analytics open"
  Write-Host "    5. Run ETL sync now:   ps-analytics etl run"
  Write-Host ""
  Write-Host "  Project directory: $ProjectDir"
  Write-Host "==================================================" -ForegroundColor Green
  Write-Host ""
}

Main
